# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='orders.Status'),
        ),
    ]
