# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171212_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='comments',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
