# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171212_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
    ]
